apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning workspace"
        rm -rf /workspace/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  steps:
    - name: run-tests
      image: python:3.11-slim
      workingDir: /workspace
      script: |
        #!/bin/sh
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install nose
        nosetests -v